version: '3.1'

services:
  app:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
  gh-pages:
    image: nginx
    ports:
      - 8082:80
    volumes:
      - ./docs:/usr/share/nginx/html:ro
